// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrnujmpzaxrkzkhdhiof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybnVqbXB6YXhya3praGRoaW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NjMzMTksImV4cCI6MjA1MjQzOTMxOX0.CmlQVtDxRHqFhShdef-veFjMco1iqVzWgnguf5y66sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);